version: '3'
services:
  flask:
    build: .
    ports:
      - "5001:5001"
    networks:
      - "redis-net"
  redis:
    image: "redis:alpine"
    command: [ "redis-server", "--appendonly", "yes" ]
    hostname: redis
    networks:
      - redis-net
networks:
    redis-net:
